language: java
jdk:
  - oraclejdk8
install: chmod +x ./gradlew
before_script: ./gradlew setupDecompWorkspace
script: ./gradlew test
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "irc.esper.net#TheSteamTank"
    template:
      - "%{repository_name}/%{branch}#%{build_number} (%{commit}): %{message}"
    use_notice: true
    skip_join: true
